import { DataModel } from "./model/data-model";
import { ProductModel } from "./model/product-data-model";

export const mensItem: Array<ProductModel> = [
  {
    id: 1,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/1.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/1.2.png",
    name: "TBBT: Bazinga",
    Category: "Oversized T-Shirts",
    price: "999",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/1.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/1.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/1.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/1.4.png",
    ],
  },
  {
    id: 2,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/2.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/2.2.png",
    name: "Naruto: Hokage",
    Category: "Oversized T-Shirts",
    price: "799",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/2.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/2.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/2.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/2.4.png",
    ],
  },
  {
    id: 3,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/3.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/3.2.png",
    name: "Spider-Man: The Web",
    Category: "T-Shirts",
    price: "599",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/3.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/3.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/3.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/3.4.png",
    ],
  },
  {
    id: 4,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/4.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/4.2.png",
    name: "Rick And Morty: Space Adventure",
    Category: "Holiday Shirts",
    price: "1199",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/4.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/4.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/4.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/4.4.png",
    ],
  },
  {
    id: 5,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/5.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/5.2.png",
    name: "The Office: Dunder Mifflin's Patt...",
    Category: "Holiday Shirts",
    price: "1299",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/5.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/5.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/5.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/5.4.png",
    ],
  },
  {
    id: 6,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/6.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/6.2.png",
    name: "Archie: Comic Strip",
    Category: "Holiday Shirts",
    price: "1199 1399 14%",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/6.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/6.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/6.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/6.4.png",
    ],
  },
  {
    id: 7,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/7.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/7.2.png",
    name: "Peanuts: Old School",
    Category: "T-Shirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/7.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/7.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/7.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/7.4.png",
    ],
  },
  {
    id: 8,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/8.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/8.2.png",
    name: "Black Panther: Fighter Black",
    Category: "Men Hooded Vests",
    price: "499 899 44%",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/8.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/8.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/8.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/8.4.png",
    ],
  },
  {
    id: 9,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/9.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/9.2.png",
    name: "Supima: Black",
    Category: "Supima T-Shirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/9.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/9.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/9.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/9.4.png",
    ],
  },
  {
    id: 10,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/10.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/10.2.png",
    name: "Supima: Baltic Sea",
    Category: "Supima T-Shirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/10.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/10.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/10.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/10.4.png",
    ],
  },
  {
    id: 11,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/11.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/11.2.png",
    name: "Batman: 7",
    Category: "Men Hooded Vests",
    price: "799",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/11.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/11.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/11.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/11.4.png",
    ],
  },
  {
    id: 12,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/12.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/12.2.png",
    name: "Spider-Man: Comics (Utility)",
    Category: "Men Cargo Joggers",
    price: "1499",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/12.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/12.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/12.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/12.4.png",
    ],
  },
  {
    id: 13,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/13.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/13.2.png",
    name: "Justice League: Logo",
    Category: "Men Joggers",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/13.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/13.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/13.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/13.4.png",
    ],
  },
  {
    id: 14,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/14.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/14.2.png",
    name: "Superman: Man of Steel (Utility)",
    Category: "Men Cargo Joggers",
    price: "1499",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/14.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/14.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/14.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/14.4.png",
    ],
  },
  {
    id: 15,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/15.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/15.2.png",
    name: "Solids: Eggshell White",
    Category: "Men Cargo Joggers",
    price: "1749",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/15.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/15.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/15.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/15.4.png",
    ],
  },
  {
    id: 16,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/16.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/16.2.png",
    name: "Solids: Burgundy",
    Category: "Men Cargo Joggers",
    price: "1999",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/16.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/16.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/16.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/16.4.png",
    ],
  },
  {
    id: 17,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/17.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/17.2.png",
    name: "Solids: Mid Blue Wash (Straigh...",
    Category: "Men Jeans",
    price: "2299",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/17.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/17.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/17.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/17.4.png",
    ],
  },
  {
    id: 18,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/18.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/18.2.png",
    name: "Solids: Ash Grey (Straight Fit)",
    Category: "Men Cargo Jeans",
    price: "2499",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/18.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/18.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/18.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/18.4.png",
    ],
  },
  {
    id: 19,
    Display_image: "./src/img/Mens/Mens-Productpage-Img's/19.1.png",
    hover_Image: "./src/img/Mens/Mens-Productpage-Img's/19.2.png",
    name: "Solids: Ice Blue (Straight Fit)",
    Category: "Men Jeans",
    price: "2299",
    quantity: 1,
    moreImage: [
      "./src/img/Mens/Mens-Productpage-Img's/19.1.png",
      "./src/img/Mens/Mens-Productpage-Img's/19.2.png",
      "./src/img/Mens/Mens-Productpage-Img's/19.3.png",
      "./src/img/Mens/Mens-Productpage-Img's/19.4.png",
    ],
  },
];

export const MensData: DataModel = {
  sliderImages: [
    "./src/img/Mens/Mens-Productpage-Img's/Top-slider/1.png",
    "./src/img/Mens/Mens-Productpage-Img's/Top-slider/2.png",
    "./src/img/Mens/Mens-Productpage-Img's/Top-slider/3.png",
  ],

  breadcrumbData: { path: "men", page: "Mens-Section" },
  mensItem: mensItem,

  options: {
    product: [
      "T-shirts",
      "Shirts",
      "Oversized T-shirts",
      "joggers",
      "jeans",
      "Polos",
      "Supima",
    ],

    size: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4-5Y",
      "5-6Y",
      "6-7Y",
      "7-8Y",
      "8-9Y",
      "9-10Y",
      "10-11Y",
      "11-12Y",
      "12-14Y",
    ],
  },
};

export const womensItem: Array<ProductModel> = [
  {
    id: 20,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/1.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/1.2.png",
    name: "TSS: Candy Colourblock",
    Category: "Women Oversized Cropped Shirts",
    price: "1499",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/1.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/1.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/1.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/1.4.png",
    ],
  },
  {
    id: 21,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/2.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/2.2.png",
    name: "TSS: Dazed",
    Category: "Women Boyfriend Shirts",
    price: "1499",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/2.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/2.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/2.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/2.4.png",
    ],
  },
  {
    id: 22,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/3.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/3.2.png",
    name: "Harry Potter: Hogwarts",
    Category: "Women Oversized Cropped Shirts",
    price: "1299",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/3.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/3.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/3.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/3.4.png",
    ],
  },
  {
    id: 23,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/4.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/4.2.png",
    name: "Solids: Blue Stripes",
    Category: "Women Boyfriend Shirts",
    price: "1199",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/4.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/4.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/4.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/4.4.png",
    ],
  },
  {
    id: 24,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/5.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/5.2.png",
    name: "Peanuts: Buddies",
    Category: "Women Boxy Fit Shirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/5.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/5.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/5.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/5.4.png",
    ],
  },
  {
    id: 25,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/6.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/6.2.png",
    name: "Women's Denim Shirt: Raw Blue",
    Category: "Denim Shirts",
    price: "999 1399 28%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/6.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/6.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/6.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/6.4.png",
    ],
  },
  {
    id: 26,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/7.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/7.2.png",
    name: "Powerpuff Girls: Bubbles Set",
    Category: "Women Co-ord Sets",
    price: "1799",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/7.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/7.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/7.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/7.4.png",
    ],
  },
  {
    id: 27,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/8.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/8.2.png",
    name: "Solids: Lavender Love Set",
    Category: "Women Co-ord Sets",
    price: "1599 1799 11%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/8.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/8.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/8.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/8.4.png",
    ],
  },
  {
    id: 28,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/9.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/9.2.png",
    name: "Harry Potter: Hedwig Pattern Set",
    Category: "Women Co-ord Sets",
    price: "1599",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/9.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/9.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/9.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/9.4.png",
    ],
  },
  {
    id: 29,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/10.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/10.2.png",
    name: "Solids: Burgundy",
    Category: "Women Dresses",
    price: "1699",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/10.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/10.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/10.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/10.4.png",
    ],
  },
  {
    id: 30,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/11.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/11.2.png",
    name: "TSS Originals: Queen",
    Category: "Women Dresses",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/11.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/11.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/11.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/11.4.png",
    ],
  },
  {
    id: 31,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/12.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/12.2.png",
    name: "Solids: Navy",
    Category: "Skater Dresses",
    price: "899 1199 25%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/12.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/12.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/12.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/12.4.png",
    ],
  },
  {
    id: 32,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/13.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/13.2.png",
    name: "Wonder Woman: Colourblock",
    Category: "MSweatshirt Dresses",
    price: "1199 1499 20%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/13.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/13.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/13.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/13.4.png",
    ],
  },
  {
    id: 33,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/14.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/14.2.png",
    name: "Solids: Grey Rib Knit",
    Category: "Women Sweater Dresses",
    price: "1199 1499 20%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/14.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/14.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/14.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/14.4.png",
    ],
  },
  {
    id: 34,
    Display_image: "./src/img/Womens/Womens-Productpage-Img's/15.1.png",
    hover_Image: "./src/img/Womens/Womens-Productpage-Img's/15.2.png",
    name: "Solids: Lavender",
    Category: "Polo Dresses",
    price: "799 999 20%",
    quantity: 1,
    moreImage: [
      "./src/img/Womens/Womens-Productpage-Img's/15.1.png",
      "./src/img/Womens/Womens-Productpage-Img's/15.2.png",
      "./src/img/Womens/Womens-Productpage-Img's/15.3.png",
      "./src/img/Womens/Womens-Productpage-Img's/15.4.png",
    ],
  },
];

export const WomensData: DataModel = {
  sliderImages: [
    "./src/img/Womens/Womens-Productpage-Img's/Top-slider/1.png",
    "./src/img/Womens/Womens-Productpage-Img's/Top-slider/2.png",
    "./src/img/Womens/Womens-Productpage-Img's/Top-slider/3.png",
  ],

  breadcrumbData: { path: "women", page: "Womens-Section" },
  mensItem: womensItem,

  options: {
    product: [
      "Women Oversized Cropped Shirts",
      "Women Boyfriend Shirts",
      "Women Boxy Fit Shirts",
      "Denim Shirts",
      "Women Co-ord Sets",
      "Women Dresses",
      "Skater Dresses",
      "MSweatshirt Dresses",
      "Women Sweater Dresses",
      "Polo Dresses",
    ],

    size: ["XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL"],
  },
};

export const kidsItem: Array<ProductModel> = [
  {
    id: 35,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/1.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/1.2.png",
    name: "PSG: Messi",
    Category: "Boys Cotton Oversized T-Shirts",
    price: "699",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/1.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/1.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/1.3.png",
      "./src/img/Kids/Kids-Productpage-Img's/1.4.png",
    ],
  },
  {
    id: 36,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/2.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/2.2.png",
    name: "Marvel: Logo",
    Category: "Boys Cotton Oversized T-Shirts",
    price: "799",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/2.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/2.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/2.3.png",
    ],
  },
  {
    id: 37,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/3.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/3.2.png",
    name: "Powerpuff Girls: Fierce",
    Category: "Girls Cotton Crop Tops",
    price: "499",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/3.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/3.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/3.3.png",
    ],
  },

  {
    id: 38,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/4.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/4.2.png",
    name: "The Lion King: Simba and Mufasa",
    Category: "Boys Cotton T-Shirts",
    price: "599",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/4.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/4.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/4.3.png",
    ],
  },

  {
    id: 39,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/5.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/5.2.png",
    name: "Harry Potter: Hedwig",
    Category: "Girls Cotton Hoodies",
    price: "999",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/5.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/5.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/5.3.png",
    ],
  },

  {
    id: 40,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/6.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/6.2.png",
    name: "Gryffindor: Sweat Block",
    Category: "Boys Cotton Sweatshirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/6.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/6.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/6.3.png",
    ],
  },

  {
    id: 40,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/7.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/7.2.png",
    name: "Avengers: Cut and Sew",
    Category: "Boys Puffer Jackets",
    price: "1899",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/7.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/7.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/7.3.png",
    ],
  },

  {
    id: 41,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/8.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/8.2.png",
    name: "Superman: Man Of Steel Set",
    Category: "Boys Cotton Co-ord Sets",
    price: "999 1299 23%",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/8.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/8.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/8.3.png",
      "./src/img/Kids/Kids-Productpage-Img's/8.4.png",
    ],
  },
  {
    id: 42,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/9.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/9.2.png",
    name: "Space Traveller: Glow In The Dark",
    Category: "Boys Cotton T-Shirts",
    price: "449",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/9.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/9.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/9.3.png",
      "./src/img/Kids/Kids-Productpage-Img's/9.4.png",
    ],
  },
  {
    id: 43,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/10.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/10.2.png",
    name: "Disney: Chip 'N Dale Pattern",
    Category: "Girls Cotton T-Shirts",
    price: "399",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/10.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/10.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/10.3.png",
    ],
  },

  {
    id: 43,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/11.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/11.2.png",
    name: "Looney Tunes: Lola Bunny",
    Category: "Girls Cotton Full Sleeve T-Shirts",
    price: "499",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/11.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/11.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/11.3.png",
    ],
  },

  {
    id: 44,
    Display_image: "./src/img/Kids/Kids-Productpage-Img's/12.1.png",
    hover_Image: "./src/img/Kids/Kids-Productpage-Img's/12.2.png",
    name: "Looney Tunes: Bugs Bunny",
    Category: "Girls Cotton Sweatshirts",
    price: "899",
    quantity: 1,
    moreImage: [
      "./src/img/Kids/Kids-Productpage-Img's/12.1.png",
      "./src/img/Kids/Kids-Productpage-Img's/12.2.png",
      "./src/img/Kids/Kids-Productpage-Img's/12.3.png",
    ],
  },
];

export const KidsData: DataModel = {
  breadcrumbData: { path: "kid", page: "Kids-Section" },
  mensItem: kidsItem,

  options: {
    product: [
      "Boys Cotton Oversized T-Shirts",
      "Girls Cotton Crop Tops",
      "Boys Cotton T-Shirts",
      "Girls Cotton Hoodies",
      "Boys Cotton Sweatshirts",
      "Boys Puffer Jackets",
      "Boys Cotton Co-ord Sets",
      "Girls Cotton T-Shirts",
      "Girls Cotton Full Sleeve T-Shirts",
      "Girls Cotton Sweatshirts",
    ],

    size: [
      "2-3Y",
      "3-4Y",
      "4-5Y",
      "5-6Y",
      "6-7Y",
      "7-8Y",
      "8-9Y",
      "9-10Y",
      "10-11Y",
      "11-12Y",
      "12-14Y",
    ],
  },
};
